// apps/ui-library/src/lib/features/playback/playback-controls/components/player-controls.svelte
<script lang="ts">
  import { PLAYBACK_STATUS, REPEAT_OPTIONS } from '@/shared/enums'
  import { getPlaybackState } from '@/shared/contexts'
  import { IconButton } from '@/shared/components'

  const state = getPlaybackState()

  function handlePlayPause() {
    if (state.status === PLAYBACK_STATUS.Playing) {
      state.pause()
    } else {
      state.play()
    }
  }
</script>

<div
  class="player-controls"
  role="group"
  aria-label="Playback Controls"
>
  <IconButton
    color="secondary"
    aria-label="Shuffle"
    onclick={() => state.toggleShuffle()}
    class="player-controls__secondary-action"
  >
    <i class:inactive={!state.shuffle}>shuffle</i>
  </IconButton>

  <IconButton
    aria-label="Previous"
    disabled={!state.hasPrevious}
    onclick={() => state.previous()}
    class="player-controls__secondary-action"
  >
    <i>skip_previous</i>
  </IconButton>

  <IconButton
    aria-label={state.status === PLAYBACK_STATUS.Playing ? 'Pause' : 'Play'}
    onclick={handlePlayPause}
    variant="filled"
  >
    {#if state.status === PLAYBACK_STATUS.Playing}
      <i>pause</i>
    {:else}
      <i>play_arrow</i>
    {/if}
  </IconButton>

  <IconButton
    aria-label="Next"
    disabled={!state.hasNext}
    onclick={() => state.next()}
  >
    <i>skip_next</i>
  </IconButton>

  <IconButton
    aria-label="Repeat"
    onclick={() => state.toggleRepeat()}
    class="player-controls__secondary-action"
  >
    {#if state.repeat === REPEAT_OPTIONS.None}
      <i class:inactive={true}>repeat</i>
    {:else if state.repeat === REPEAT_OPTIONS.All}
      <i>repeat</i>
    {:else if state.repeat === REPEAT_OPTIONS.Single}
      <i>repeat_one</i>
    {/if}
  </IconButton>
</div>

<style lang="scss">
  .player-controls {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 8px;
  }

  .inactive {
    opacity: var(--state-disabled-layer-opacity);
  }
</style>

// apps/web/src/app/features/player/components/player-controls/player-controls.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core'
import { playerSelectors } from '@selectors'

import { PlayerStatus, RepeatOption } from '@core/enum'
import { AudioState, PlaybackState } from '@core/state'

@Component({
  selector: 'neko-player-controls',
  templateUrl: 'player-controls.component.html',
  styleUrls: ['player-controls.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlayerControlsComponent {
  private readonly playbackState = inject(PlaybackState)
  private readonly audioState = inject(AudioState)

  readonly repeatOption = RepeatOption
  readonly playerStatus = PlayerStatus

  readonly selectors = playerSelectors

  readonly status = this.audioState.status
  readonly repeat = this.playbackState.repeat
  readonly shuffle = this.playbackState.shuffle
  readonly hasPrevious = this.playbackState.hasPrevious
  readonly hasNext = this.playbackState.hasNext

  handleTogglePlay() {
    this.audioState.togglePlay()
  }

  handleToggleRepeat() {
    this.playbackState.toggleRepeat()
  }

  handleSkipNext() {
    this.playbackState.next()
  }

  handleSkipPrevious() {
    this.playbackState.previous()
  }

  handleToggleShuffle() {
    this.playbackState.toggleShuffle()
  }
}

<button
  [class]="{ inactive: !shuffle() }"
  [selector]="selectors.shuffleButton"
  aria-label="Shuffle"
  class="neko-player-controls-shuffle-button"
  nekoIconButton
  variant="text"
  (click)="handleToggleShuffle()"
>
  <i>shuffle</i>
</button>

<button
  [disabled]="!hasPrevious()"
  [selector]="selectors.skipPreviousButton"
  aria-label="Previous"
  class="neko-player-controls-previous-button"
  nekoIconButton
  variant="text"
  (click)="handleSkipPrevious()"
>
  <i>skip_previous</i>
</button>

<button
  [selector]="selectors.playButton"
  aria-label="Play"
  color="secondary"
  nekoIconButton
  (click)="handleTogglePlay()"
>
  @switch (status()) {
    @case (playerStatus.Playing) {
      <i>pause</i>
    }
    @case (playerStatus.Loading) {
      <i>downloading</i>
    }
    @case (playerStatus.Paused) {
      <i>play_arrow</i>
    }
  }
</button>

<button
  [disabled]="!hasNext()"
  [selector]="selectors.skipNextButton"
  aria-label="Next"
  nekoIconButton
  variant="text"
  (click)="handleSkipNext()"
>
  <i>skip_next</i>
</button>

<button
  [selector]="selectors.repeatButton"
  aria-label="Repeat"
  nekoIconButton
  variant="text"
  (click)="handleToggleRepeat()"
>
  @switch (repeat()) {
    @case (repeatOption.None) {
      <i class="inactive">repeat</i>
    }
    @case (repeatOption.All) {
      <i>repeat</i>
    }
    @case (repeatOption.Single) {
      <i>repeat_one</i>
    }
  }
</button>
